query productISBNs($first: Int!, $after: String) {
  products(first: $first, after: $after) {
    pageInfo {
      hasNextPage
    }
    edges {
      cursor
      node {
        id
        variants(first: 1) {
          edges {
            node {
              barcode
            }
          }
        }
      }
    }
  }
}
