query products($first: Int!, $after: String) {
  products(first: $first, after: $after) {
    pageInfo {
      hasNextPage
    }
    edges {
      cursor
      node {
        handle
        descriptionHtml
        metafield(namespace: "global", key: "ebook") {
          namespace
          value
        }
      }
    }
  }
}
