# https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/finding-and-customizing-actions#referencing-an-action-in-the-same-repository-where-a-workflow-file-uses-the-action

name: 'Setup bazel'
description: 'setting up bazel using bazelisk via Node.js'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        # https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#pull-request-events
        ref: ${{ github.head_ref }}
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.3
      with:
        node-version: 12.x
    - name: Restore caches
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ~/.cache/bazel
          ./node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-
    - run: yarn install
