name: deploy contents

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.1
        with:
          node-version: 15.x
      - name: Restore caches
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-
      - run: yarn install
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: "k9bookshelf-bazel-cache"
          service_account_key: ${{ secrets.GCP_BAZEL_CACHE_KEY }}
          export_default_credentials: true
      - run: make -s deploy/contents
        if: github.ref == 'refs/heads/main'
        env:
          MARKDOWN_APP_KEY: ${{ secrets.MARKDOWN_APP_KEY }}
          MARKDOWN_APP_SECRET: ${{ secrets.MARKDOWN_APP_SECRET }}
          GRAPHQL_ADMIN_API_SECRET: ${{ secrets.GRAPHQL_ADMIN_API_SECRET }}
