name: deploy theme

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 15.x
      - name: Restore caches
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-
      - run: yarn install
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: "k9bookshelf-bazel-cache"
          service_account_key: ${{ secrets.GCP_BAZEL_CACHE_KEY }}
          export_default_credentials: true
      - run: make lint
      - run: make deploy/theme
        if: github.ref == 'refs/heads/main'
        env:
          THEME_APP_SECRET: ${{ secrets.THEME_APP_SECRET }}
          THEME_ID: ${{ secrets.THEME_ID }}
          LOGROCKET_APP_NAME: ${{ secrets.LOGROCKET_APP_NAME }}
