name: deploy contents

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 15.x
      - name: Restore caches
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-
      - run: yarn install
      - run: make deploy/contents
        if: github.ref == 'refs/heads/main'
        env:
          MARKDOWN_APP_SECRET: ${{ secrets.MARKDOWN_APP_SECRET }}
          GRAPHQL_ADMIN_API_SECRET: ${{ secrets.GRAPHQL_ADMIN_API_SECRET }}
