name: test go

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 15.x
      - name: Restore caches
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-
      - run: yarn install
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: "k9bookshelf-bazel-cache"
          service_account_key: ${{ secrets.GCP_BAZEL_CACHE_KEY }}
          export_default_credentials: true
      - run: npx bazel test //...
